language:       go
go:             ['1.18.x', '1.19.x']
go_import_path: github.com/teamwork/reload
jobs:
  include:
    - {'os': 'linux',   'arch': 'amd64'}
    - {'os': 'linux',   'arch': 'amd64'}
    - {'os': 'linux',   'arch': 'arm64'}
    - {'os': 'linux',   'arch': 'ppc64le'}
    - {'os': 'linux',   'arch': 's390x'}
    - {'os': 'osx',     'arch': 'amd64'}
    - {'os': 'windows', 'arch': 'amd64'}

notifications:
  email: false
install:
script: |
  export GO111MODULE=on
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
  bash <(curl -s https://codecov.io/bash)
